name: Make Docker
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ENV
      run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Setup Docker Build X
      uses: docker/setup-buildx-action@v2
    - name: Log into container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ env.TAG }}
        build-args: |
          VERSION=${{ env.TAG }}